"""

image generated by each "observation"

"""

import numpy as np
import matplotlib.pyplot as plt




class image():
    
    def __init__(self,w,h):
        
        self.width = w
        self.height = h
        
        self.image = np.zeros(shape=(self.height,self.width))
    
    
    def add_random_noise(self):
        
        self.image
    
    
    
    def generate_image(self):
        
        return self.image
        


def generate_image():
    
    w = 150
    h = 100
    img = image(w,h)
    
    im = img.generate_image()
    
    plt.imshow(im)
    plt.show()


if __name__ == "__main__":
    
    generate_image()
    
    
    
    
    
    